version: "3.9"

services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    command: ./wait-for.sh redis:6379 -- /home/node/app/node_modules/.bin/nodemon index.js

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379" 
    command: "redis-server --requirepass ${REDIS_PASS}"

volumes:
  node_modules: